### ISSUE TITLE
Connecting app to a database

### ISSUE THREAD

**Issue by lurichen** [lululinda/MUAContactApp#2]
Hola @dashr ,

Ya que lanzamos el app a Heroku https://tranquil-springs-72542.herokuapp.com, queriamos saber si nos puedes dar apoyo en como conectarlo a un base de datos (mySQL) y configurar el servidor para ver si el app esta funcionando y guardando los datos que se entren desde la app. Queremos ver si esto esta funcionando al final de hoy.

**Comment by dashr** [comment]
Con este PR se puede resolver, sin tener que montar todo un backend y base de datos mas complejo. No require SQL. 

https://github.com/lululinda/MUAContactApp/pull/3

**Comment by dashr** [comment]
se agrego y se guardan los datos
